Add logging service
Jakub-Zochowski/epam-node-course pull request #5
Opened 2022-01-14 17:36 UTC by Jakub-Zochowski

2022-01-18 15:04 UTC, Dmitry-White requested changes
Left a couple of comments.

2022-01-24 23:25 UTC, Jakub-Zochowski commented on task-3/services/logging.ts
> +	static logger = (method: string, ...args: any[]) => {
I've added a route and service logger so that I get logs that will be more helpful to identify where the issue happened.

2022-01-24 23:26 UTC, Jakub-Zochowski commented on task-3/services/group.ts
> +		LoggingService.logger('addUsersToGroup', arguments[0]);
I like the idea of having different scope so I use that. While logging I use the scope as well as route/method and arguments or body and params. To make it easier to debug.

2022-01-25 12:33 UTC, Dmitry-White approved these changes

2022-01-25 12:33 UTC, Dmitry-White commented on task-3/services/logging.ts
> +	routeLogger = (req: any, res: any, next: any) => {
While this is already much better in terms of the usability, it's still not that common for loggers to be aware of the implementation details of where they're used.
Approving the PR, but do pay attention to the concept of "Log Levels" and do some further reading on it.
https://blog.appsignal.com/2021/09/01/best-practices-for-logging-in-nodejs.html

2022-01-27 15:12 UTC, merged